let fruit = ["banana","grapes","apple","orange"];
fruit.push("melon");
console.log(fruit);
console.log(fruit.pop());
fruit.pop();
console.log(fruit);
fruit.unshift("water");
console.log(fruit);
fruit.shift();
console.log(fruit);